// src/data/products.js
import samFero from '../media/sam-fero.jpg';
import samCalciumD3 from '../media/samCalciumD3.jpg';
import samCollagen from '../media/samCollagen.jpg';
import samQ10 from '../media/samQ10.jpg';
import sanJointFlex from '../media/sanJointFlex.jpg';
import samGery from '../media/samGery.jpg';
import samVitaminD3 from '../media/samVitaminD3.jpg';
import samOmega from '../media/samOmega.jpg';
import samNerveHealth from '../media/samNerveHealth.jpg';

export const products = [
  // 1. SAM JOINT FLEX
  {
    id: 1,
    name: 'SAM JOINT FLEX',
    nameAr: 'سام جونت - فليكس',
    nameFr: 'SAM JOINT FLEX',
    nameEs: 'SAM JOINT FLEX',
    slug: 'sam-joint-flex',
    category: 'joints',
    categoryAr: 'المفاصل والعظام',
    categoryEn: 'Joints & Bones',
    categoryFr: 'Articulations et os',
    categoryEs: 'Articulaciones y huesos',
    description: 'Glucosamine Sulfate 2000mg supports joint health and cartilage rebuilding. MSM 1500mg reduces inflammation. Hyaluronic Acid 90mg maintains joint lubrication. Contains Collagen, Ginger & Turmeric Extract 400mg for anti-inflammatory effects. Black Pepper Extract 5mg for enhanced absorption. Vitamin C 100mg, Vitamin D3 2000 IU, plus Molybdenum, Manganese, Zinc, and Magnesium for complete bone and joint support.',
    descriptionAr: 'جلوكوزامين 2000 مجم لتحسين صحة المفاصل وإعادة بناء الغضاريف. MSM 1500 مجم لتقليل الالتهابات. حمض الهيالورونيك 90 مجم للحفاظ على ليونة وترطيب المفاصل. يحتوي على كولاجين، مستخلص الزنجبيل والكركم 400 مجم كمضادات فعالة للالتهابات. بيبيرين 5 مجم لتعزيز الامتصاص. فيتامين C 100 مجم، فيتامين D3 2000 وحدة، ومعادن الموليبدينوم والمنجنيز والزنك والمغنيسيوم لدعم صحة المفاصل والعظام.',
    descriptionFr: 'La glucosamine sulfate 2000 mg soutient la santé des articulations et la reconstruction du cartilage. MSM 1500 mg réduit l\'inflammation. Acide hyaluronique 90 mg maintient la lubrification articulaire.',
    descriptionEs: 'La glucosamina sulfato 2000 mg favorece la salud de las articulaciones y la reconstrucción del cartílago. MSM 1500 mg reduce la inflamación.',
    size: '١٢٠ كبسولة',
    sizeEn: '120 Capsules',
    sizeFr: '120 Gélules',
    sizeEs: '120 Cápsulas',
    sizeOptions: ['١٢٠ كبسولة'],
    sizeOptionsEn: ['120 Capsules'],
    sizeOptionsFr: ['120 Gélules'],
    sizeOptionsEs: ['120 Cápsulas'],
    hashtags: ['JointFlex', 'Glucosamine', 'MSM', 'HyaluronicAcid', 'Turmeric', 'Collagen', 'VitaminD3'],
    image: sanJointFlex,
    featured: true,
  },

  // 2. SAM TRIPLE OMEGA
  {
    id: 2,
    name: 'SAM TRIPLE OMEGA',
    nameAr: 'سام تربل أوميغا',
    nameFr: 'SAM TRIPLE OMEGA',
    nameEs: 'SAM TRIPLE OMEGA',
    slug: 'sam-triple-omega',
    category: 'supplements',
    categoryAr: 'مكملات غذائية',
    categoryEn: 'Supplements',
    categoryFr: 'Compléments alimentaires',
    categoryEs: 'Suplementos',
    description: 'Balanced blend of 2600mg Omega 3-6-9. Contains Flaxseed Oil 1000mg, Borage Oil 800mg, Fish Oil 800mg rich in EPA & DHA. Supports heart health, brain function, reduces inflammation.',
    descriptionAr: 'مزيج متوازن بتركيز 2600 مجم من أوميغا 3-6-9. يحتوي على زيت بذر الكتان 1000 مجم، زيت لسان الثور 800 مجم، زيت السمك 800 مجم الغني بـ EPA و DHA.',
    descriptionFr: 'Mélange équilibré de 2600 mg d\'oméga 3-6-9. Contient de l\'huile de lin 1000 mg, de l\'huile de bourrache 800 mg.',
    descriptionEs: 'Mezcla equilibrada de 2600 mg de Omega 3-6-9. Contiene aceite de linaza 1000 mg, aceite de borraja 800 mg.',
    size: '٣٠ كبسولة',
    sizeEn: '30 Capsules',
    sizeFr: '30 Gélules',
    sizeEs: '30 Cápsulas',
    sizeOptions: ['٣٠ كبسولة', '٩٠ كبسولة', '١٨٠ كبسولة'],
    sizeOptionsEn: ['30 Capsules', '90 Capsules', '180 Capsules'],
    sizeOptionsFr: ['30 Gélules', '90 Gélules', '180 Gélules'],
    sizeOptionsEs: ['30 Cápsulas', '90 Cápsulas', '180 Cápsulas'],
    hashtags: ['Omega3', 'Omega369', 'FishOil', 'HeartHealth', 'BrainHealth', 'FlaxseedOil'],
    image: samOmega,
    featured: true,
  },

  // 3. SAM VITAMIN D
  {
    id: 3,
    name: 'SAM VITAMIN D',
    nameAr: 'سام فيتامين D',
    nameFr: 'SAM VITAMINE D',
    nameEs: 'SAM VITAMINA D',
    slug: 'sam-vitamin-d',
    category: 'vitamins',
    categoryAr: 'فيتامينات',
    categoryEn: 'Vitamins',
    categoryFr: 'Vitamines',
    categoryEs: 'Vitaminas',
    description: 'High potency Vitamin D3 10,000 IU in vegan hard capsules. Supports bone and teeth health, immune system function.',
    descriptionAr: 'فيتامين D3 بتركيز عالٍ 10,000 وحدة دولية في كبسولات نباتية. يعزز امتصاص الكالسيوم والفوسفور، ويدعم جهاز المناعة.',
    descriptionFr: 'Vitamine D3 haute puissance 10 000 UI en gélules végétaliennes.',
    descriptionEs: 'Vitamina D3 de alta potencia 10,000 UI en cápsulas veganas.',
    size: '٩٠ كبسولة',
    sizeEn: '90 Capsules',
    sizeFr: '90 Gélules',
    sizeEs: '90 Cápsulas',
    sizeOptions: ['٩٠ كبسولة', '١٨٠ كبسولة'],
    sizeOptionsEn: ['90 Capsules', '180 Capsules'],
    sizeOptionsFr: ['90 Gélules', '180 Gélules'],
    sizeOptionsEs: ['90 Cápsulas', '180 Cápsulas'],
    hashtags: ['VitaminD3', 'HighPotency', 'Vegan', 'BoneHealth', 'Immunity'],
    image: samVitaminD3,
    featured: true,
  },

  // 4. SAM FERRO
  {
    id: 4,
    name: 'SAM FERRO',
    nameAr: 'سام فيرو',
    nameFr: 'SAM FERRO',
    nameEs: 'SAM FERRO',
    slug: 'sam-ferro',
    category: 'minerals',
    categoryAr: 'معادن وفيتامينات',
    categoryEn: 'Minerals & Vitamins',
    categoryFr: 'Minéraux et vitamines',
    categoryEs: 'Minerales y vitaminas',
    description: 'Advanced iron formula with Dried Ferrous Sulfate 65mg. Contains Lactoferrin 150mg and Folic Acid 400 mcg.',
    descriptionAr: 'تركيبة حديد فائقة مع كبريتات حديدوز مجففة 65 مجم. يحتوي على لاكتوفيرين 150 مجم وحمض الفوليك 400 ميكروجرام.',
    descriptionFr: 'Formule avancée de fer avec sulfate ferreux séché 65 mg. Contient de la lactoferrine 150 mg.',
    descriptionEs: 'Fórmula avanzada de hierro con sulfato ferroso seco 65 mg. Contiene lactoferrina 150 mg.',
    size: '٣٠ كبسولة',
    sizeEn: '30 Capsules',
    sizeFr: '30 Gélules',
    sizeEs: '30 Cápsulas',
    sizeOptions: ['٣٠ كبسولة'],
    sizeOptionsEn: ['30 Capsules'],
    sizeOptionsFr: ['30 Gélules'],
    sizeOptionsEs: ['30 Cápsulas'],
    hashtags: ['Iron', 'Ferro', 'Lactoferrin', 'FolicAcid', 'Anemia'],
    image: samFero,
    featured: false,
  },

  // 5. SAM GREY
  {
    id: 5,
    name: 'SAM GREY',
    nameAr: 'سام غري',
    nameFr: 'SAM GREY',
    nameEs: 'SAM GREY',
    slug: 'sam-grey',
    category: 'beauty',
    categoryAr: 'الجمال والشعر',
    categoryEn: 'Beauty & Hair',
    categoryFr: 'Beauté et cheveux',
    categoryEs: 'Belleza y cabello',
    description: 'Powerful antioxidant blend with Vitamin E, C, B-Vitamin complex, and essential minerals for hair health.',
    descriptionAr: 'مزيج قوي من مضادات الأكسدة مع فيتامين E و C ومجموعة فيتامينات B والمعادن الأساسية لصحة الشعر.',
    descriptionFr: 'Mélange antioxydant puissant avec vitamines E, C, complexe B et minéraux essentiels.',
    descriptionEs: 'Mezcla antioxidante poderosa con vitaminas E, C, complejo B y minerales esenciales.',
    size: '٦٠ كبسولة',
    sizeEn: '60 Capsules',
    sizeFr: '60 Gélules',
    sizeEs: '60 Cápsulas',
    sizeOptions: ['٦٠ كبسولة', '١٨٠ كبسولة'],
    sizeOptionsEn: ['60 Capsules', '180 Capsules'],
    sizeOptionsFr: ['60 Gélules', '180 Gélules'],
    sizeOptionsEs: ['60 Cápsulas', '180 Cápsulas'],
    hashtags: ['GreyHair', 'Biotin', 'Melanin', 'HairLoss', 'AntiAging'],
    image: samGery,
    featured: true,
  },

  // 6. SAM NERVE HEALTH
  {
    id: 6,
    name: 'SAM NERVE HEALTH',
    nameAr: 'سام نيرف هيلث',
    nameFr: 'SAM SANTÉ NERVEUSE',
    nameEs: 'SAM SALUD NERVIOSA',
    slug: 'sam-nerve-health',
    category: 'supplements',
    categoryAr: 'صحة الأعصاب',
    categoryEn: 'Nerve Health',
    categoryFr: 'Santé nerveuse',
    categoryEs: 'Salud nerviosa',
    description: 'Alpha Lipoic Acid 500mg with B-Vitamins (B1, B6, B12) for nerve health support.',
    descriptionAr: 'حمض الليبويك 500 مجم مع فيتامينات B لدعم صحة الأعصاب.',
    descriptionFr: 'Acide alpha-lipoïque 500 mg avec vitamines B pour la santé nerveuse.',
    descriptionEs: 'Ácido alfa-lipoico 500 mg con vitaminas B para la salud nerviosa.',
    size: '٣٠ كبسولة',
    sizeEn: '30 Capsules',
    sizeFr: '30 Gélules',
    sizeEs: '30 Cápsulas',
    sizeOptions: ['٣٠ كبسولة'],
    sizeOptionsEn: ['30 Capsules'],
    sizeOptionsFr: ['30 Gélules'],
    sizeOptionsEs: ['30 Cápsulas'],
    hashtags: ['NerveHealth', 'AlphaLipoicAcid', 'VitaminB12', 'Neuropathy'],
    image: samNerveHealth,
    featured: false,
  },

  // 7. SAM Q-10
  {
    id: 7,
    name: 'SAM Q-10',
    nameAr: 'سام كيو-10',
    nameFr: 'SAM Q-10',
    nameEs: 'SAM Q-10',
    slug: 'sam-q10',
    category: 'supplements',
    categoryAr: 'صحة القلب',
    categoryEn: 'Heart Health',
    categoryFr: 'Santé cardiaque',
    categoryEs: 'Salud cardíaca',
    description: 'Coenzyme Q10 400mg for heart health and cellular protection.',
    descriptionAr: 'إنزيم Q10 بتركيز 400 مجم لصحة القلب والحماية الخلوية.',
    descriptionFr: 'Coenzyme Q10 400 mg pour la santé cardiaque.',
    descriptionEs: 'Coenzima Q10 400 mg para la salud cardíaca.',
    size: '٣٠ كبسولة',
    sizeEn: '30 Capsules',
    sizeFr: '30 Gélules',
    sizeEs: '30 Cápsulas',
    sizeOptions: ['٣٠ كبسولة'],
    sizeOptionsEn: ['30 Capsules'],
    sizeOptionsFr: ['30 Gélules'],
    sizeOptionsEs: ['30 Cápsulas'],
    hashtags: ['CoQ10', 'HeartHealth', 'Energy', 'Antioxidant'],
    image: samQ10,
    featured: true,
  },

  // 8. SAM CALCIUM
  {
    id: 8,
    name: 'SAM CALCIUM',
    nameAr: 'سام كالسيوم',
    nameFr: 'SAM CALCIUM',
    nameEs: 'SAM CALCIO',
    slug: 'sam-calcium',
    category: 'minerals',
    categoryAr: 'معادن',
    categoryEn: 'Minerals',
    categoryFr: 'Minéraux',
    categoryEs: 'Minerales',
    description: 'Calcium 90mg from oyster shell with Vitamin D3 2000 IU for bone health.',
    descriptionAr: 'كالسيوم 90 مجم من قشر المحار مع فيتامين D3 2000 وحدة لصحة العظام.',
    descriptionFr: 'Calcium 90 mg de coquille d\'huître avec vitamine D3 2000 UI.',
    descriptionEs: 'Calcio 90 mg de concha de ostra con vitamina D3 2000 UI.',
    size: '٩٠ كبسولة',
    sizeEn: '90 Capsules',
    sizeFr: '90 Gélules',
    sizeEs: '90 Cápsulas',
    sizeOptions: ['٩٠ كبسولة', '١٨٠ كبسولة'],
    sizeOptionsEn: ['90 Capsules', '180 Capsules'],
    sizeOptionsFr: ['90 Gélules', '180 Gélules'],
    sizeOptionsEs: ['90 Cápsulas', '180 Cápsulas'],
    hashtags: ['Calcium', 'VitaminD3', 'BoneHealth', 'OysterShell'],
    image: samCalciumD3,
    featured: false,
  },

  // 9. SAM COLLAGEN
  {
    id: 9,
    name: 'SAM COLLAGEN',
    nameAr: 'سام كولاجين',
    nameFr: 'SAM COLLAGÈNE',
    nameEs: 'SAM COLÁGENO',
    slug: 'sam-collagen',
    category: 'beauty',
    categoryAr: 'الجمال والبشرة',
    categoryEn: 'Beauty & Skin',
    categoryFr: 'Beauté et peau',
    categoryEs: 'Belleza y piel',
    description: 'Hydrolyzed Marine Collagen 1000mg for skin elasticity, joint health, and hair strength.',
    descriptionAr: 'كولاجين بحري متحلل 1000 مجم لمرونة البشرة وصحة المفاصل.',
    descriptionFr: 'Collagène marin hydrolysé 1000 mg pour l\'élasticité de la peau.',
    descriptionEs: 'Colágeno marino hidrolizado 1000 mg para la elasticidad de la piel.',
    size: '١٢٠ كبسولة',
    sizeEn: '120 Capsules',
    sizeFr: '120 Gélules',
    sizeEs: '120 Cápsulas',
    sizeOptions: ['١٢٠ كبسولة', '١٨٠ كبسولة'],
    sizeOptionsEn: ['120 Capsules', '180 Capsules'],
    sizeOptionsFr: ['120 Gélules', '180 Gélules'],
    sizeOptionsEs: ['120 Cápsulas', '180 Cápsulas'],
    hashtags: ['Collagen', 'MarineCollagen', 'SkinHealth', 'Beauty', 'AntiAging'],
    image: samCollagen,
    featured: true,
  },
];

// Helper functions
export const getProductById = (id) => products.find(p => p.id === parseInt(id));
export const getProductBySlug = (slug) => products.find(p => p.slug === slug);
export const getFeaturedProducts = () => products.filter(p => p.featured);
export const getProductsByCategory = (category) => products.filter(p => p.category === category);
export const getProductsByHashtag = (hashtag) => products.filter(p => 
  p.hashtags.some(tag => tag.toLowerCase() === hashtag.toLowerCase())
);
